baseURL                = 'https://nogoodev.ru/'
defaultContentLanguage = "en"

summaryLength = 7 # first sentence

googleAnalytics = "G-L9BMG9JD0J"
# title = 'Bad Dev'

enableEmoji         = true
enableGitInfo       = true
cleanDestinationDir = true
enableRobotsTXT     = true

[pagination]
    pagerSize = 7
[minify]
    minifyOutput = true

[permalinks]
    [permalinks.page]
        blog   = '/blog/:slug/'
        docs   = '/docs/:slug/'
        things = '/things/:slug/'

[frontmatter]
    date = [
        'date',
        'publishDate',
    ]
    expiryDate = [
        'expiryDate',
    ]
    lastmod = [
        ':git',
        'lastmod',
        'publishDate',
    ]
    publishDate = [
        'date',
        'publishDate',
    ]

[imaging]
    bgColor        = '#ffffff'
    hint           = 'photo'
    quality        = 85
    resampleFilter = "Lanczos"

[related]
    includeNewer = true
    threshold    = 80
    toLower      = false
    [[related.indices]]
        applyFilter          = false
        cardinalityThreshold = 0
        name                 = 'keywords'
        pattern              = ''
        toLower              = false
        type                 = 'basic'
        weight               = 100
    [[related.indices]]
        applyFilter          = false
        cardinalityThreshold = 0
        name                 = 'tags'
        pattern              = ''
        toLower              = false
        type                 = 'basic'
        weight               = 80

[outputs]
    home = [
        "html",
        "json",
        "rss",
    ]
    page = [
        'html',
    ]
    rss = [
        'rss',
    ]
    section = [
        'html',
        'rss',
    ]
    taxonomy = [
        'html',
        'rss',
    ]
    term = [
        'html',
        'rss',
    ]
