baseURL                = 'https://HOOTORO.github.io/'
defaultContentLanguage = "en"

paginate      = 10
summaryLength = 10

googleAnalytics = "G-L9BMG9JD0J"

[outputs]
    home = [
        "HTML",
        "JSON",
        "RSS",
    ]
    section = [
        'html',
        'rss',
    ]
    taxonomy = [
        'html',
    ]
    term = [
        'html',
    ]
