baseURL                = 'https://HOOTORO.github.io/'
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate        = 5
summaryLength   = 0

googleAnalytics = "G-L9BMG9JD0J"

[outputs]
    home = [
        "HTML",
        "JSON",
        "RSS",
    ]
