# title = 'Bad Dev'

enableEmoji         = true
enableGitInfo       = true
cleanDestinationDir = true

[minify]
    minifyOutput = true

[permalinks]
    [permalinks.page]
        blog = '/blog/:slug/'
        docs = '/docs/:slug/'

[frontmatter]
    date = [
        'date',
        'lastmod',
        'publishDate',
    ]
    expiryDate = [
        'expiryDate',
    ]
    lastmod = [
        ':git',
        'date',
        'lastmod',
        'publishDate',
    ]
    publishDate = [
        'date',
        'publishDate',
    ]

[imaging]
    bgColor        = '#ffffff'
    hint           = 'photo'
    quality        = 85
    resampleFilter = "Lanczos"

[related]
    includeNewer = true
    threshold    = 80
    toLower      = false
    [[related.indices]]
        applyFilter          = false
        cardinalityThreshold = 0
        name                 = 'keywords'
        pattern              = ''
        toLower              = false
        type                 = 'basic'
        weight               = 100
    [[related.indices]]
        applyFilter          = false
        cardinalityThreshold = 0
        name                 = 'tags'
        pattern              = ''
        toLower              = false
        type                 = 'basic'
        weight               = 80
