title                  = 'Bad Dev'
baseURL                = 'https://HOOTORO.github.io/'
languageCode           = 'en-us'
enableEmoji            = true
enableGitInfo          = true
enableRobotsTXT        = true
defaultContentLanguage = 'en'
cleanDestinationDir    = true

[module]
    noProxy       = 'none'
    noVendor      = ''
    private       = '*.*'
    proxy         = 'direct'
    vendorClosest = false
    workspace     = 'off'

    [module.hugoVersion]
        extended = true
        min      = "0.129.0"
    [[module.imports]]
        path    = "github.com/hugo-sid/hugo-blog-awesome"
        disable = false
[permalinks]
    [permalinks.page]
        blog = '/blog/:slug/'
        docs = '/docs/:slug/'

[frontmatter]
    date = [
        'date',
        'lastmod',
        'publishDate',
    ]
    expiryDate = [
        'expiryDate',
    ]
    lastmod = [
        ':git',
        'date',
        'lastmod',
        'publishDate',
    ]
    publishDate = [
        'date',
        'publishDate',
    ]

[menu]
    [[menu.main]]
        name    = 'Home'
        pageRef = "/"
        weight  = 10
    [[menu.main]]
        pre     = '<i class="fa-solid fa-code"></i>'
        name    = 'Blog'
        pageRef = '/blog'
        weight  = 20
    [[menu.main]]
        pre     = '<i class="fa fa-heart"></i>'
        name    = 'Doc'
        pageRef = '/docs'
        weight  = 80
    [[menu.main]]
        name    = '<'
        pageRef = '/about'
        weight  = 90
[imaging]
    bgColor        = '#ffffff'
    hint           = 'photo'
    quality        = 85
    resampleFilter = "Lanczos"
