# title = 'Bad Dev'

enableEmoji         = true
enableGitInfo       = true
cleanDestinationDir = true

[minify]
    minifyOutput = true

[permalinks]
    [permalinks.page]
        blog = '/blog/:slug/'
        docs = '/docs/:slug/'

[frontmatter]
    date = [
        'date',
        'lastmod',
        'publishDate',
    ]
    expiryDate = [
        'expiryDate',
    ]
    lastmod = [
        ':git',
        'date',
        'lastmod',
        'publishDate',
    ]
    publishDate = [
        'date',
        'publishDate',
    ]

[imaging]
    bgColor        = '#ffffff'
    hint           = 'photo'
    quality        = 85
    resampleFilter = "Lanczos"
