languageCode      = 'en'
languageName      = "English"
languageDirection = "ltr"
weight            = 1

title     = "#dev.lc"
copyright = "© 2024 HOOTORO, _right?_ :thinking_face:"

[params]
    dateFormat  = "2 January 2006"
    description = "Не хороший разработчик пишет"
    creation    = '18.07.2023'

    mainSections = [
        "doc",
        "post",
    ]
    [params.author]
        name = "HOOTORO"
        image = "av.png"
        headline = "Bad Dev is always typing..."
        bio = "Bad Dev"
        links = [
            { dev = "https://dev.to/hootoro" },
            { discord = "https://discordid.netlify.app/?id=88370628763078656" },
            { github = "https://github.com/HOOTORO/" },
            { reddit = "https://www.reddit.com/u/HOOTORO/" },
            { telegram = "https://t.me/HOOTORO" },
            { twitch = "https://www.twitch.tv/hootoro" },
            { youtube = "https://www.youtube.com/@HOOTORO" },
        ]
