defaultMarkdownHandler = 'goldmark'
[tableOfContents]
    startLevel = 2
    endLevel   = 4
[highlight]
    noClasses = false
[goldmark]
    [goldmark.renderer]
        hardWraps = true
        unsafe    = true
    [goldmark.renderHooks]
        [goldmark.renderHooks.image]
            enableDefault = true
        [goldmark.renderHooks.link]
            enableDefault = true
[goldmark.extensions]
    definitionList  = true
    footnote        = true
    linkify         = true
    linkifyProtocol = 'https'
    strikethrough   = true
    table           = true
    [goldmark.extensions.extras]
        [goldmark.extensions.extras.insert]
            enable = true
        [goldmark.extensions.extras.mark]
            enable = true
[goldmark.parser]
    autoHeadingID                      = true
    autoHeadingIDType                  = 'github'
    wrapStandAloneImageWithinParagraph = true
    [goldmark.parser.attribute]
        block = true
        title = true
