defaultMarkdownHandler = 'goldmark'
[tableOfContents]
    endLevel   = 4
    startLevel = 2
    ordered    = false
[highlight]
    noClasses = false
[goldmark]
    [goldmark.renderer]
        hardWraps = true
        unsafe    = true
        xhtml     = false
    [goldmark.renderHooks]
        [goldmark.renderHooks.image]
            enableDefault = true
        [goldmark.renderHooks.link]
            enableDefault = true
[goldmark.extensions]
    definitionList  = true
    footnote        = true
    linkify         = true
    linkifyProtocol = 'https'
    strikethrough   = true
    table           = true
    [goldmark.extensions.extras]
        [goldmark.extensions.extras.insert]
            enable = true
        [goldmark.extensions.extras.mark]
            enable = true
        [goldmark.extensions.extras.subscript]
            enable = false
        [goldmark.extensions.extras.superscript]
            enable = false
[goldmark.parser]
    autoHeadingID                      = true
    autoHeadingIDType                  = 'github'
    wrapStandAloneImageWithinParagraph = true
    [goldmark.parser.attribute]
        block = true
        title = true
