[[main]]
    name    = '<'
    pageRef = '/'
    weight  = 10
[[main]]
    name    = 'Blog'
    pageRef = '/blog'
    weight  = 20
    [main.params]
        icon = 'admo/abstract'
[[main]]
    name    = 'Doc'
    pageRef = '/docs'
    weight  = 30
    [main.params]
        icon = 'admo/cog'
[[main]]
    name    = 'Hooketize'
    pageRef = '/hooketize'
    weight  = 40
    [main.params]
        icon = 'admo/new'
[[main]]
    name    = '\>'
    pageRef = '/about'
    weight  = 50
[[main]]
    url    = 'https://github.com/HOOTORO/'
    weight = 90
    [main.params]
        rel    = 'external'
        target = "_blank"
        icon   = 'github'

[[footer]]
    name    = "Tags"
    pageRef = "tags"
    weight  = 30
[[footer]]
    name    = 'Categories'
    pageRef = 'categories'
    weight  = 20
[[footer]]
    name    = 'Things'
    pageRef = 'things'
    weight  = 10
    [footer.params]
        icon = 'admo/tip'

        # [[footer]]
        #     name    = "Privacy"
        #     pageRef = "privacy"
        #     weight  = 30
        # [[main]]
        #     parent  = 'These'
        #     name    = 'Things'
        #     weight  = 80
        #     pageRef = 'things'
        #     [main.params]
        #         class = 'center'
        # [[main]]
        #     parent  = 'Env'
        #     name    = 'These'
        #     weight  = 90
        #     pageRef = 'these'
        #    pre    = '<i class="fa fa-heart"></i>'
        #    pre     = "<i class='fa fa-road'></i>"
        #    pre     = '<i class="fa fa-heart"></i>'
        #    pre     = '<i class="fa-solid fa-code"></i>'
        # -- Footer Menu --
        # The footer menu is displayed at the bottom of the page, just before
        # the copyright notice. Configure as per the main menu above.
