noProxy       = 'none'
noVendor      = ''
private       = '*.*'
proxy         = 'direct'
vendorClosest = false
workspace     = 'off'

[hugoVersion]
    extended = true
    min      = "0.134.*"
[[imports]]
    path    = "github.com/jpanther/congo/v2"
    disable = false
