##!HUGOAweesome
### congo vars

colorScheme          = "congo" # sapphire   ocean   congo   slate  cherry  avocado
defaultAppearance    = "dark"
autoSwitchAppearance = false

defaultThemeColor = "#111014"

enableSearch           = true
enableCodeCopy         = true
enableImageLazyLoading = true
enableQuicklink        = true
enableImageWebp        = true

fingerprintAlgorithm = "sha256"

# custom 
prcSubTypes = [
    'bmp',
    'png',
    'tiff',
]

# hours 168 = 7 days
newLabelExpiredAfter = 168
mainSections = [
    "doc",
    "post",
]
[header]
    layout    = "hybrid"
    logo      = "images/main-logo.png"
    logoDark  = "images/second-logo.png"
    showTitle = true
[homepage]
    layout      = "profile" # profile   page
    showRecent  = true
    recentLimit = 5
[footer]
    showCopyright          = true
    showThemeAttribution   = true
    showAppearanceSwitcher = true
    showScrollToTop        = true

[article]
    showDate            = false
    showDateUpdated     = false
    showAuthor          = false
    showBreadcrumbs     = true
    showDraftLabel      = true
    showEdit            = true
    editURL             = "https://github.com/HOOTORO/hootoro.github.io/tree/main/content"
    editAppendPath      = true
    showHeadingAnchors  = true
    showPagination      = true
    invertPagination    = false
    showReadingTime     = false
    showTableOfContents = false
    showTaxonomies      = false
    showWordCount       = false
    showComments        = false

    sharingLinks = [
        "email",
        "facebook",
        "line",
        "linkedin",
        "mastodon",
        "pinterest",
        "reddit",
        "telegram",
        "threads",
        "weibo",
        "x-twitter",
    ]

[list]
    showBreadcrumbs     = true
    showSummary         = true
    showTableOfContents = false
    showTaxonomies      = false
    groupByYear         = true
    paginationWidth     = 1

    # [sitemap]
    # excludedKinds = [
    #     "taxonomy",
    #     "term",
    # ]

[taxonomy]
    showTermCount = true

[hb]
    color           = 'light'
    css_bundle_name = 'hb'
    debug           = false
    full_width      = false
    js_bundle_name  = 'hb'
    logo            = 'images/logo.png'
