#* HUGO congo theme *#
#*      vars        *#

#! sapphire   ocean   congo   slate  cherry  avocado

colorScheme       = "ocean"
defaultAppearance = "dark"
defaultThemeColor = "#111014"

autoSwitchAppearance   = false
enableSearch           = true
enableCodeCopy         = true
enableImageLazyLoading = true
enableQuicklink        = true
enableImageWebp        = true

fingerprintAlgorithm = "sha256"

#! custom 
prcSubTypes = [
    'bmp',
    'png',
    'tiff',
]
#! hours 168 = 7 days
newLabelExpiredAfter = 168

mainSections = [
    "doc",
    "post",
]
[header]
    layout    = "hybrid"
    logo      = "images/main-logo.png"
    logoDark  = "images/second-logo.png"
    showTitle = true
[homepage]
    layout      = "profile" #! profile page
    showRecent  = true
    recentLimit = 5
[footer]
    showCopyright          = true
    showThemeAttribution   = true
    showAppearanceSwitcher = true
    showScrollToTop        = true

[article]
    showHeadingAnchors  = true
    showBreadcrumbs     = true
    showDraftLabel      = true
    showEdit            = true
    showPagination      = true
    showReadingTime     = true
    editAppendPath      = true
    editURL             = "https://github.com/HOOTORO/hootoro.github.io/tree/main/content"
    invertPagination    = false
    showWordCount       = true
    showTableOfContents = false
    showComments        = false
    showTaxonomies      = true
    showDate            = true
    showDateUpdated     = false
    showAuthor          = true

    sharingLinks = [
        "email",
        "facebook",
        "line",
        "linkedin",
        "mastodon",
        "pinterest",
        "reddit",
        "telegram",
        "threads",
        "weibo",
        "x-twitter",
    ]

[list]
    showBreadcrumbs     = true
    showSummary         = true
    groupByYear         = true
    showTableOfContents = false
    showTaxonomies      = false
    paginationWidth     = 1

[sitemap]
    excludedKinds = [
        "taxonomy",
        "term",
    ]

[taxonomy]
    showTermCount = true
