##!HUGOAweesome
### congo vars

colorScheme          = "avocado" # sapphire   ocean   congo   slate  cherry
defaultAppearance    = "dark"
autoSwitchAppearance = false

defaultThemeColor = "#111014"

enableSearch           = true
enableCodeCopy         = true
enableImageLazyLoading = true
enableQuicklink        = true
enableImageWebp        = true

fingerprintAlgorithm = "sha256"

# custom 
prcSubTypes = [
    'bmp',
    'png',
    'tiff',
]

# hours 168 = 7 days
newLabelExpiredAfter = 168

[header]
    layout = "hybrid"
    # logo      = "favicon.ico"
    # logoDark  = "favicon.ico"
    showTitle = true
[homepage]
    layout      = "profile" # profile   page
    showRecent  = false
    recentLimit = 3
[footer]
    showCopyright          = true
    showThemeAttribution   = true
    showAppearanceSwitcher = true
    showScrollToTop        = true

[article]
    showDate            = true
    showDateUpdated     = false
    showAuthor          = true
    showBreadcrumbs     = true
    showDraftLabel      = true
    showEdit            = true
    editURL             = "https://github.com/HOOTORO/hootoro.github.io"
    editAppendPath      = true
    showHeadingAnchors  = true
    showPagination      = true
    invertPagination    = false
    showReadingTime     = true
    showTableOfContents = true
    showTaxonomies      = true
    showWordCount       = true
    showComments        = false

    sharingLinks = [
        "email",
        "facebook",
        "line",
        "linkedin",
        "mastodon",
        "pinterest",
        "reddit",
        "telegram",
        "threads",
        "weibo",
        "x-twitter",
    ]

[list]
    showBreadcrumbs     = true
    showSummary         = true
    showTableOfContents = false
    showTaxonomies      = false
    groupByYear         = true
    paginationWidth     = 2

    # [sitemap]
    # excludedKinds = [
    #     "taxonomy",
    #     "term",
    # ]

[taxonomy]
    showTermCount = true
