##!HUGOAweesome
### congo vars

colorScheme          = "sapphire"
defaultAppearance    = "dark"
autoSwitchAppearance = false

defaultThemeColor = "#111014"

enableSearch           = true
enableCodeCopy         = true
enableImageLazyLoading = true
enableQuicklink        = true
enableImageWebp        = true

# robots = ""
fingerprintAlgorithm = "sha256"

# custom 
prcSubTypes = [
    'bmp',
    'png',
    'tiff',
]
resizeRatio = 2
maxWidth = 1000
[header]
    layout   = "hybrid"
    logo     = "favicon.ico"
    logoDark = "favicon.ico"
[homepage]
    layout     = "profile"
    showRecent = true
[footer]
    showCopyright          = true
    showThemeAttribution   = true
    showAppearanceSwitcher = true
    showScrollToTop        = true

[article]
    showDate            = true
    showDateUpdated     = false
    showAuthor          = true
    showBreadcrumbs     = false
    showDraftLabel      = true
    showEdit            = true
    editURL             = "https://github.com/HOOTORO/hootoro.github.io/"
    editAppendPath      = true
    showHeadingAnchors  = true
    showPagination      = true
    invertPagination    = false
    showReadingTime     = true
    showTableOfContents = true
    showTaxonomies      = true
    showWordCount       = true
    showComments        = false

    sharingLinks = [
        "email",
        "facebook",
        "line",
        "linkedin",
        "mastodon",
        "pinterest",
        "reddit",
        "telegram",
        "threads",
        "weibo",
        "x-twitter",
    ]

[list]
    showBreadcrumbs     = false
    showSummary         = true
    showTableOfContents = false
    showTaxonomies      = false
    groupByYear         = true
    paginationWidth     = 2

[sitemap]
    excludedKinds = [
        "taxonomy",
        "term",
    ]

[taxonomy]
    showTermCount = true
    series        = 'series'
